### ISSUE TITLE
[BUG] Broken with 1.13.5

### ISSUE THREAD

**Issue by harry1453** [Zingabopp/MultiplayerExtensions#103]
**Multiplayer Extensions Version and Download Source**
v0.4.5 from GitHub

**Your Platform**
PC/Steam

**Describe the bug**
When you start a level in a lobby, the countdown starts for the host but not for any clients. When the countdown ends, you get an infinite loading wheel.

**To Reproduce**

1. Try to play multiplayer with any level, it just doesn't work. BeatTogether and official servers both produce the same result.

**Expected behavior**
The level loads and is played.

**Log**
[2021.03.12.21.47.35.log.gz](https://github.com/Zingabopp/MultiplayerExtensions/files/6148779/2021.03.12.21.47.35.log.gz)

**Screenshots/Video**

**Additional context**

**Comment by BeauGieskens** [comment]
I found that this was happening only with vanilla songs; custom songs seem to work just fine in my case.

**Comment by JAJames** [comment]
It looks like this is already fixed with PR #99, the maintainer just needs to cut a new release.

**Comment by Goobwabber** [comment]
new version out on releases
