### ISSUE TITLE
[BUG] Mod installed but not working with new update.

### ISSUE THREAD

**Issue by SmartFolk** [Zingabopp/MultiplayerExtensions#105]
**Multiplayer Extensions Version and Download Source**
0.4.7.0 from the github

**Your Platform**
Steam RiftS PC

**Describe the bug**
Since the most recent steam update mod has not been working for me I don't know if this is just a me issue or if the mod needs to be updated to be compatable.

**To Reproduce**
Download and install the new release and place in plugins folder then launch the game and create a server.

**Expected behavior**
The expected behavior is for custom songs to be enabled.

**Log**
[_latest.log](https://github.com/Zingabopp/MultiplayerExtensions/files/6206033/_latest.log)

**Additional context**
I could just be trolling and all that needs to happen is an update or this could be a legitimate issue for me help is appriciated.

**Comment by Zingabopp** [comment]
You're missing a dependency (SiraUtil v2.5.2+). `[WARNING @ 11:37:40 | IPA/Loader] MultiplayerExtensions is missing dependency SiraUtil@^2.5.2` . Should work once you install that.
