### ISSUE TITLE
[BUG] Can't join Crossplay Games (Steam)

### ISSUE THREAD

**Issue by AhegaHOE** [Zingabopp/MultiplayerExtensions#108]
**Multiplayer Extensions Version and Download Source**
v.0.4.7 - GitHub Download

**Your Platform**
PC - Steam, no custom launch options:

**Describe the bug**
Im not able to join games that are marked as Crossplay via [ServerBrowser](https://github.com/roydejong/BeatSaberServerBrowser)
After waiting some time in a loading screen the error: "CFR-3 (Server Unreachable) Could not connect to the host." pops up. 

**To Reproduce**
1. Start up your Game
2. Click on 'Online'
3. Click on 'Server Browser'
3. Scroll to a Game that is marked as 'Crossplay' and try to join it
4. Wait until the loading stops and see the error.

**Log**
[_latest.log](https://github.com/Zingabopp/MultiplayerExtensions/files/6257550/_latest.log)

**Screenshots/Video**
https://user-images.githubusercontent.com/73001005/113562613-b5437800-9606-11eb-9b5b-a9ce68b003dd.mp4

**Comment by Goobwabber** [comment]
This is an issue with BeatTogether/a general networking issue on your end. You can ask for help in their discord: https://discord.com/invite/gezGrFG4tz
