### ISSUE TITLE
[BUG] Selecting specific songs cause desyncs

### ISSUE THREAD

**Issue by bloofirephoenix** [Zingabopp/MultiplayerExtensions#109]
**Multiplayer Extensions Version and Download Source**
v0.4.7 from Mod Assistant

**Your Platform**
Both players are on PC/Steam

**Describe the bug**
When selecting some songs (Example: https://beatsaver.com/beatmap/8d49) the song will not appear for the other players regardless of if they have it installed or not. Whoever selected the song will stop moving for the other players. However, the selector can still see the others move. If another song is selected or suggested after it, the selector will not see the selected/suggested song. If the game is started, the selector will not see the countdown or enter the game.

The selector must leave and re-enter the lobby to continue playing.

**To Reproduce**
1. Download the example song (https://beatsaver.com/beatmap/8d49)
2. Enter/Create a lobby
3. Select the example song.

**Expected behavior**
The song should appear and be playable by everyone.

**Logs**
[host-log.log](https://github.com/Zingabopp/MultiplayerExtensions/files/6283361/host-log.log)
[player-log.log](https://github.com/Zingabopp/MultiplayerExtensions/files/6283362/player-log.log)

**Additional context**
This may be related to #59 but the player is not kicked and the bug happens regardless of if the host has the song

**Comment by A-plou** [comment]
that's only the ping difference, if someone have a poor connection, with multiplayer extension or any private match. 
at least 1 player will be desync because of the connection, but it doesn't do that if both connection is stable.

**Comment by bloofirephoenix** [comment]
But how would this song specifically cause ping issues? Me and my friend are able to play many different songs with no problems until somebody suggests the specific song I brought up in the example. We both have the song downloaded as well.

**Comment by A-plou** [comment]
I don't know about that, I know it happen to me sometimes with some song

**Comment by bloofirephoenix** [comment]
It seems you may have been right. After selecting the song and waiting for a little while it eventually appeared and played normally.

I have decided to close this issue as it seems to be a problem unrelated to MultiplayerExtensions.
