### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by roboltz** [Zingabopp/MultiplayerExtensions#110]
**Multiplayer Extensions Version and Download Source**
Latest version of 4/10/21 v0.4.7
**Your Platform**
Oculus Quest hooked up to PC with a Cable. Custom Launch Options: -vrmode oculus

**Describe the bug**
When trying to join a game with either server browser or through password the game says: "Could not connect to the server. Check your internet connection and try again (CFR-3)" even with good internet.

**To Reproduce**

1. Go to 'Online'
2. Click on 'Join with Code or server browser if mod is installed'
3. Type code or join a game with same version mod
4. See error (this is only for me, i don't understand how to make the glitch happen)

**Expected behavior**
To be able to join a game with code or on server browser.

**Log**
I don't know what log to show so I will show both logs for beat saber and Multiplayer Extensions:
MultiplayerExtensions Log: [2021.04.09.20.50.36.log](https://github.com/Zingabopp/MultiplayerExtensions/files/6290707/2021.04.09.20.50.36.log)
Beat Saber Log: [2021.04.09.20.50.31.log](https://github.com/Zingabopp/MultiplayerExtensions/files/6290713/2021.04.09.20.50.31.log)

**Screenshots/Video**
https://streamable.com/jnhxkx

**Additional context**
Problem still stays without -vrmode oculus

**Comment by A-plou** [comment]
https://github.com/pythonology/BeatTogether/issues/9
I think you have that bug

**Comment by Goobwabber** [comment]
BeatTogether bug, cant fix

**Comment by roboltz** [comment]
this is a multiplayer extensions bug, I deleted everything that was beat together in my files yet it still happens
