### ISSUE TITLE
[FEATURE] Random song selection in private games

### ISSUE THREAD

**Issue by ItsCharaHere** [Zingabopp/MultiplayerExtensions#111]
**Is your feature request related to a problem? Please describe.**
Somewhat, when people are conflicted on what song to play and the host has no idea which one to choose.

**Describe the solution you'd like**
Using the random song selection feature from quickplay.

**Additional context**
Basically it really, just adding a toggle for host that uses the random song selection that people have chosen as the suggested song

**Comment by Goobwabber** [comment]
Implemented in #117
