### ISSUE TITLE
[BUG] Can't get Customs songs to work, and no log to analyse!

### ISSUE THREAD

**Issue by ThaChillera** [Zingabopp/MultiplayerExtensions#112]
**Multiplayer Extensions Version and Download Source**
v0.4.7 from github release

**Your Platform**
Steam, HTC Vive, Arch Linux

**Describe the bug**
No custom level option in a multiplayer lobby. Also no logs anywhere in the beast saber install folder, so I can't really analyze what the issue is

**Expected behavior**
Custom songs in MP, or at least a log telling me whats happening

**Log**
Yeah that's missing :/

**Additional comments**
Singleplayer working as expected, including custom songs!
I've followed every troubleshooting step, triple-checked required mods & mod versions are present & correct. I just can't do the final step: look at the log, cause there is none for some bizarre reason

Any help would be greatly appreciated

**Comment by Zingabopp** [comment]
If there is no MpEx log that means the mod isn't loading at all, which indicates an installation problem. Check the big log in `Logs\_latest.log` (if you don't have that, then you don't have any mods working), and see if it says anything about MultiplayerExtensions.

**Comment by Enrique-Groeneveld** [comment]
Have you fixed it yet because i have the same problems.

**Comment by Zingabopp** [comment]
I would need the whole game log I mentioned above. This is like not a problem with MultiplayerExtensions (otherwise it wouldn't work for anybody), but with the way you installed it.

**Comment by Enrique-Groeneveld** [comment]
i just got it working. I did it by manually going through al the needed mods and reinstalling them by hand instead of with mod assistant and then it worked fine .

**Comment by ThaChillera** [comment]
Yeah, it was BISPA not working - I was under the impression single player custom songs was a modded feature, thus sending me down all the wrong paths

For any future searchers: vague instructions at https://bsmg.github.io/BeatSaber-IPA-Reloaded/tags/4.1.6/articles/start-user.html#Note

summary: running on linux requires some dll overrides for your wine prefix, download the .reg file from the link and apply it using protontricks :)
