### ISSUE TITLE
[BUG] Sorting Buttons stop working after clicking Random and Playing a Song

### ISSUE THREAD

**Issue by CrimseyVT** [Zingabopp/MultiplayerExtensions#113]
**Multiplayer Extensions Version and Download Source**
https://github.com/Zingabopp/MultiplayerExtensions/releases/tag/v0.4.7

**Your Platform**
Steam > -vrmode oculus

**Describe the bug**
Sorting buttons stop working after playing a Randomly chosen song?

**To Reproduce**
This Video explains it all. https://streamable.com/x3j86a

**Expected behavior**
To sort songs properly.. As in if i click sort by PP it sorts by PP, not stops working entirely.

**Log**
[_latest.log](https://github.com/Zingabopp/MultiplayerExtensions/files/6364546/_latest.log)

**Screenshots/Video**
https://streamable.com/x3j86a Same Video as linked above. ^

**Additional context**

**Comment by A-plou** [comment]
#93 
I don't know if it's come to the same type of bug of that one, but I believe it is 
I believe multiplayer doesn't fully support filter and random song at the moment

**Comment by Goobwabber** [comment]
Thank you for the comprehensive report, but I believe this is an issue with [SongBrowser](https://github.com/halsafar/BeatSaberSongBrowser). You can create a new issue there.
