### ISSUE TITLE
[BUG] MultiplayerExtensions downgrades to 0.4.3 when launching Beat Saber

### ISSUE THREAD

**Issue by SilentGamer475** [Zingabopp/MultiplayerExtensions#114]
**Multiplayer Extensions Version and Download Source**
https://github.com/Zingabopp/MultiplayerExtensions/releases/tag/v0.4.7, released on March 20th, 2021.

**Your Platform**
Steam, Valve Index

**Describe the bug**
MultiplayerExxtensions downgrades its version from 0.4.7 to 0.4.3 whenever I launch beat saber.

**To Reproduce**
Download any form of MultiplayerExtensions 0.4.7, run Beat Saber, MultiplayerExtensions is now 0.4.3. Nobody else has seem to have this issue, so that's as well as I can explain it.

**Expected behavior**
MultiplayerExtensions stays at its current patch when running Beat Saber, not downgrading.

**Log**
[_latest.log](https://github.com/Zingabopp/MultiplayerExtensions/files/6368943/_latest.log)

**Screenshots/Video**
Before launching: 
![image](https://user-images.githubusercontent.com/53794180/115945744-a6701880-a482-11eb-88e9-face77039352.png)

After launching: (EDIT: Realized the properties were on the wrong tab. Now fixed.)
![image](https://user-images.githubusercontent.com/53794180/115948770-be04cc80-a495-11eb-93d6-c2bd4ad42660.png)

My plugins folder: 
![image](https://user-images.githubusercontent.com/53794180/115945827-1088bd80-a483-11eb-8f3c-f993cb471eca.png)

**Additional context**
This has never happened before, I starting noticing it earlier this month, probably around the 8th or 9th of April. Nobody in BSMG seemed to understand, nor has anyone else seemed to have this issue. Other than that, I've got nothing.

**Comment by Goobwabber** [comment]
could you provide a full log of this? (attach the log in the root logs folder, not the log in the multiplayerextensions folder)

**Comment by SilentGamer475** [comment]
> could you provide a full log of this? (attach the log in the root logs folder, not the log in the multiplayerextensions folder)

[_latest.log](https://github.com/Zingabopp/MultiplayerExtensions/files/6401460/_latest.log)
Sorry for not posting this sooner, I didn't have access to my PC because of school stuff so I couldn't send you the file until now.

**Comment by Goobwabber** [comment]
Check your `Beat Saber\IPA\Pending\` folders for an older version of the mod. My theory is that the 0.4.3 version of the mod might have gotten stuck there and the new version is continually replaced with it. If the mod is there, delete it and it should fix your problem.
