### ISSUE TITLE
[BUG] Handshake error on beatsaver download

### ISSUE THREAD

**Issue by ThaChillera** [Zingabopp/MultiplayerExtensions#116]
**Multiplayer Extensions Version and Download Source**
v0.4.8 from github releases

**Your Platform**
Steam, Archlinux

**Describe the bug**
Downloading custom songs don't work - the log mentions something about Handshake failure

**To Reproduce**
1. Join a friends lobby
2. Let them select a song you don't have downloaded
3. Press play, loads infinitely

**Expected behavior**
Customs song I don't have should automatically download

**Log**
The log contains all the errors to explain the issue, but I'm not sure how to solve it sadly. Is it a mono bug? A wine thing? something else entirely?
[_latest.log](https://github.com/Zingabopp/MultiplayerExtensions/files/6446273/_latest.log)

Thanks for your help!

**Comment by A-plou** [comment]
[ERROR @ 22:20:04 | MultiplayerExtensions] Error downloading beatmap 'custom_level_967D96E7DFD3EE444071E0A24DCC5FBB5B535266': An error occurred while sending the request

[DEBUG @ 22:20:04 | MultiplayerExtensions] System.Net.Http.HttpRequestException: An error occurred while sending the request ---> System.Net.WebException: Error: TrustFailure (One or more errors occurred.) ---> System.AggregateException: One or more errors occurred. ---> System.Security.Authentication.AuthenticationException: A call to SSPI failed, see inner exception. ---> Mono.Security.Interface.TlsException: Handshake failed - error code: UNITYTLS_INTERNAL_ERROR, verify result: UNITYTLS_X509VERIFY_FLAG_NOT_TRUSTED

[DEBUG @ 22:21:25 | MultiplayerExtensions] --- End of stack trace from previous location where exception was thrown ---
[DEBUG @ 22:21:25 | MultiplayerExtensions]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <9577ac7a62ef43179789031239ba8798>:0 
[DEBUG @ 22:21:25 | MultiplayerExtensions]   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <9577ac7a62ef43179789031239ba8798>:0 
[DEBUG @ 22:21:25 | MultiplayerExtensions]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <9577ac7a62ef43179789031239ba8798>:0 
[DEBUG @ 22:21:25 | MultiplayerExtensions]   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <9577ac7a62ef43179789031239ba8798>:0 
[DEBUG @ 22:21:25 | MultiplayerExtensions]   at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <9577ac7a62ef43179789031239ba8798>:0 
[DEBUG @ 22:21:25 | MultiplayerExtensions]   at MultiplayerExtensions.Downloader+<TryDownloadSongInternal>d__9.MoveNext () [0x000a5] in <17cddb6a57234031a6c3d5f4bb831f9a>:0 
[DEBUG @ 22:21:25 | MultiplayerExtensions] Download was unsuccessful.
[WARNING @ 22:21:25 | MultiplayerExtensions] (SongLoader) TryDownloadSong was unsuccessful.

here everything that the log said, there is more than 1 error, I don't want to say anything about it, but it look suspicious, I don't have issue with Multiplayer Extension for a while now (beside spectator) so I would recommend to re-install everything from nothing (clean install) directly from Steam

**Comment by Goobwabber** [comment]
networking issue, cant fix
