### ISSUE TITLE
[BUG] Early level end: lobby environment doesn't load

### ISSUE THREAD

**Issue by roydejong** [Zingabopp/MultiplayerExtensions#119]
**Multiplayer Extensions Version and Download Source**
v0.4.9 from GitHub Release

**Your Platform**
PC, Steam

**Describe the bug**
When ending a multiplayer level early (i.e. without going through the results screen), the lobby environment fails to load. Instead, the menu environment loads while the Host UI is still active. The Start button can no longer be pressed, lobby has to be recreated at this point. 

**To Reproduce**
1. Create a Server
2. Start any level with standard modifiers
3. Fail out of the level, causing an early return to lobby

NB: Doesn't have to be a fail, is reproducible with any early level end, e.g. pressing <kbd>U</kbd> on keyboard which is apparently a thing

**Expected behavior**
Lobby environment loads as expected after an early level end.

**Log**
Relevant logs:
```
[CRITICAL @ 14:44:49 | UnityEngine] MissingFieldException: Field 'MultiplayerPlayerResultsData.levelCompletionResults' not found.
[CRITICAL @ 14:44:49 | UnityEngine] LobbyGameStateController.HandleMultiplayerLevelDidFinish (MultiplayerLevelScenesTransitionSetupDataSO multiplayerLevelScenesTransitionSetupData, MultiplayerResultsData multiplayerResultsData) (at <2d05f8f85bbd4e6e9f302448a1c041d2>:0)
[CRITICAL @ 14:44:49 | UnityEngine] MenuTransitionsHelper+<>c__DisplayClass24_0.<HandleMultiplayerLevelDidFinish>b__0 (Zenject.DiContainer container) (at <2d05f8f85bbd4e6e9f302448a1c041d2>:0)
[CRITICAL @ 14:44:49 | UnityEngine] GameScenesManager+<>c__DisplayClass31_0.<PopScenes>b__1 (Zenject.DiContainer container) (at <452b81faebc640f39eaa461b0a08e03c>:0)
[CRITICAL @ 14:44:49 | UnityEngine] GameScenesManager+<ScenesTransitionCoroutine>d__36.MoveNext () (at <452b81faebc640f39eaa461b0a08e03c>:0)
[CRITICAL @ 14:44:49 | UnityEngine] UnityEngine.SetupCoroutine.InvokeMoveNext (System.Collections.IEnumerator enumerator, System.IntPtr returnValueAddress) (at <12e76cd50cc64cf19e759e981cb725af>:0)
```

**Screenshots/Video**
![image](https://user-images.githubusercontent.com/6772638/120071053-b5ec0e00-c08d-11eb-8c28-2cb0dae77b33.png)

**Additional context**
Does not happen without MpEx installed. Settings and song type (builtin/custom) seems to make no difference.

**Comment by roydejong** [comment]
This issue only happens for me when I use the release build, but it doesn't happen when I build from source. The field shouldn't be missing in either case, so uhhhhhhhhh 🤷‍♂️

just gonna quietly close this one

**Comment by steffhelbling** [comment]
Imho, this issue should not be closed.
It happens on three different installs and I don't want to install what's needed to compile from source and give my friends a new DLL.
