### ISSUE TITLE
lobby stops working 

### ISSUE THREAD

**Issue by Nugget-Whore** [Zingabopp/MultiplayerExtensions#120]
[_latest.log](https://github.com/Zingabopp/MultiplayerExtensions/files/6564904/_latest.log)
after song is finish cant start another one without making a new lobby

**Comment by steffhelbling** [comment]
I can confirm and issue #119 mentionned it also.
I just tried the last dev build but has the bug too...

**Comment by christiantusset** [comment]
i have the same problem here

**Comment by RaliiTheAvali** [comment]
Can verify that the current MPE is causing the issue, after each song played a new lobby has to be made, but after removing the MPE mod the issue stopped entirely.

**Comment by Raz0rBeam** [comment]
For me it sends me back to the main menu lobby with the multi UI still there. (not the timer and stuff in the middle tho)

**Comment by Goobwabber** [comment]
Does build [build #157](https://github.com/Zingabopp/MultiplayerExtensions/actions/runs/890514927) fix this?

**Comment by Raz0rBeam** [comment]
it does not. this is what happens after a song.
![unknown](https://user-images.githubusercontent.com/73900764/120113739-ded1d900-c149-11eb-809d-d8f870296656.png)

**Comment by steffhelbling** [comment]
Same as @Raz0rBeam on my side. It didn't fix... 🙁

**Comment by roydejong** [comment]
@steffhelbling @Raz0rBeam
Tracking this for the PR - thought that fixed it. Could you provide your `_latest.log` for that test build? Thanks!

**Comment by steffhelbling** [comment]
Here's mine!
[_latest.log](https://github.com/Zingabopp/MultiplayerExtensions/files/6566778/_latest.log)

**Comment by Raz0rBeam** [comment]
[_latest.log](https://github.com/Zingabopp/MultiplayerExtensions/files/6566808/_latest.log)
here ya go

**Comment by 40163650** [comment]
hi, just want to say the latest changes fixed it for me

**Comment by RaliiTheAvali** [comment]
NOT resolved, new issue created
