### ISSUE TITLE
[BUG] No server list option

### ISSUE THREAD

**Issue by ShadowMax** [Zingabopp/MultiplayerExtensions#122]
**Multiplayer Extensions Version and Download Source**

**Your Platform**
PC/Vive, Steam

**Describe the bug**
No server list option

**Log**
[CRITICAL @ 22:12:21 | UnityEngine] NullReferenceException: Object reference not set to an instance of an object
[CRITICAL @ 22:12:21 | UnityEngine] MultiplayerExtensions.OverrideClasses.PlayersDataModelStub+<HandleMenuRpcManagerGetSelectedBeatmap>d__10.MoveNext () (at <6304dda75a4048cfba081276ac5a8e50>:0)
[CRITICAL @ 22:12:21 | UnityEngine] --- End of stack trace from previous location where exception was thrown ---
[CRITICAL @ 22:12:21 | UnityEngine] System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () (at <9577ac7a62ef43179789031239ba8798>:0)
[CRITICAL @ 22:12:21 | UnityEngine] System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0 (System.Object state) (at <9577ac7a62ef43179789031239ba8798>:0)
[CRITICAL @ 22:12:21 | UnityEngine] UnityEngine.UnitySynchronizationContext+WorkRequest.Invoke () (at <12e76cd50cc64cf19e759e981cb725af>:0)
[CRITICAL @ 22:12:21 | UnityEngine] UnityEngine.UnitySynchronizationContext:ExecuteTasks()

**Screenshots/Video**
![20210530223841_1](https://user-images.githubusercontent.com/10102994/120116179-e9b35a80-c197-11eb-9207-998cddedefcb.jpg)
![20210530223846_1](https://user-images.githubusercontent.com/10102994/120116181-ea4bf100-c197-11eb-9c73-3ea2012ec338.jpg)

**Additional context**
Game version: 1.16.1
I download clean game from steam and install my usual mods from Mod Assistant.

**Comment by Goobwabber** [comment]
You are missing BeatsaverServerBrowser.

**Comment by ShadowMax** [comment]
> You are missing BeatsaverServerBrowser.

Oh, Thank you!
for others: https://github.com/roydejong/BeatSaberServerBrowser
