### ISSUE TITLE
[BUG] Platform colors get dim or stop working

### ISSUE THREAD

**Issue by roydejong** [Zingabopp/MultiplayerExtensions#128]
**Multiplayer Extensions Version and Download Source**
v0.5.4 from Mod Assistant

**Your Platform**
PC Steam (fpfc)

**Describe the bug / reproduction steps / screenshots**
Every time you join a game, the lights are more dim than last time.

1. When first starting the game and joining an MpEx lobby, the custom platform colors work as expected and look bright (especially visible on the right platform with full white color):

![image](https://user-images.githubusercontent.com/6772638/121566860-3875b580-ca1e-11eb-933d-4767db8eb7b4.png)

2. After leaving the lobby, and immediately rejoining the same game with the same players, positions and color settings, they start to look more dim although they are still visible:

![image](https://user-images.githubusercontent.com/6772638/121567117-7c68ba80-ca1e-11eb-9041-43de5e704bce.png)

3. After then joining a game with no other players, and rejoining the original game, the lights turn off completely:

![image](https://user-images.githubusercontent.com/6772638/121567982-76270e00-ca1f-11eb-83a3-c7c5c0cf2564.png)

The local player's platform color is fine throughout.

**Comment by roydejong** [comment]
I think there's two distinct issues here:
 - The colors never really snap to full brightness (updates until `IsColorVeryCloseToColor` is hit)
 - Sometimes the lerp factor seems to be too small(?); causing `SetColor` to be called indefinitely - may also have performance impact

**Comment by Goobwabber** [comment]
Fixed in #129
