### ISSUE TITLE
Songs dont start downloading until host hits start match

### ISSUE THREAD

**Issue by ItsCharaHere** [Zingabopp/MultiplayerExtensions#13]
When downloading a custom song you dont have the button does nothing until the host hits start song, in which clicking the button then starts the download and reloads songcore songs, heres the log.
[2020.10.27.18.40.44.log](https://github.com/Zingabopp/MultiplayerExtensions/files/5454944/2020.10.27.18.40.44.log)

**Comment by Goobwabber** [comment]
intended feature atm
