### ISSUE TITLE
Voice Chat

### ISSUE THREAD

**Issue by Zingabopp** [Zingabopp/MultiplayerExtensions#20]
Possible feature for the future. Could have the host start a server that the rest of the players would connect to for voice chat (something like what the old multiplayer mod had, but the host would act as the 'ServerHub').

**Comment by moritzuehling** [comment]
Just minimal fyi: There are already quite good voice protocols out there, like https://github.com/BananaHemic/Mumble-Unity (or a bit lower level, https://github.com/martindevans/MumbleSharp)

**Comment by Goobwabber** [comment]
Closing this issue for now, since you are working on it [here](https://github.com/Zingabopp/MultiplayerExtensions.VoiceChat).
