### ISSUE TITLE
If a non-host takes too long to download the song, they are moved to spectator

### ISSUE THREAD

**Issue by moritzuehling** [Zingabopp/MultiplayerExtensions#23]
Hi there!

first of all, thanks for this amazing mod! ♥

I just played it with a friend, it it worked mostly flawlessly. One small issue we noticed is that when downloading a song took to long for my friend, I waited until their download was completed - but once the song started, they were moved to spectator. I think there might be a timeout somewhere, maybe even in the original multiplayer code.

We could reproduce this with a couple of different songs. If I ended the game and restarted it, it worked perfectly fine for subsequent plays of the song.

The reason I believe is that this is related to download speed is that said friend has quite slow internet, and the move to spectator happened if the "Waiting for other players" phase was too long.

Again, thanks for developing this!

**Comment by livkx** [comment]
+1 happening for me too

**Comment by hamcoremusic** [comment]
The best way to avoid this is to get the host to start the game but all of the others DO NOT READY UP unless they know they have the song of the "x SONHS LOADED" prompt comes up at the top. Once everyone confirms they see the pop-up, everyone can then ready up.

**Comment by livkx** [comment]
This happens to me even if the songs loaded comes up at the top @hamcoremusic

**Comment by Goobwabber** [comment]
> This happens to me even if the songs loaded comes up at the top @hamcoremusic 

This sounds like an issue with the time it takes to load a map as well, interesting.

**Comment by hamcoremusic** [comment]
> This happens to me even if the songs loaded comes up at the top @hamcoremusic

Yea that's something I have not run into yet... Was this the mod that Bandoot was using in his recent video? He seemed to be avoiding a lot of these issues.

Again, as stated above, waiting seemed to work, but I guess if it's a giant map and heavily modded, it can screw it up.

**Comment by livkx** [comment]
I think things are just currently quite finnicky with handling the lobby/load if another player is missing the song.

Would a potential solution be to not actually start the game until we know the other player has it downloaded and ready? I.e. let the counter go down (or even don't even start the counter) but then not load either player in until the player missing the song's client has signalled it's ready to roll?

Just spitballing ideas, seems a safer way of handling it then chancing the download time will be quick enough. I've got gigabit fibre, but that doesn't matter if the beatsaver servers are running slow, or if another player had really poor internet speeds.

This also will be an issue if the beatsaver servers no longer have the referenced song, e.g. if it's been deleted, so I think it just needs to be handled in a safer manner.

**Comment by Zelrion** [comment]
Maybe helpful, maybe not, but this bug occurred for me while I was the host for the lobby.
