### ISSUE TITLE
Host/one player not loading into song

### ISSUE THREAD

**Issue by ItsCharaHere** [Zingabopp/MultiplayerExtensions#24]
When playing a song every once in a while when you start, (possibly if the host doesnt have the suggested song cant remember) the other player/players are sent into the song and the other person is stuck on the lobby screen, it was a few days since it happened so i cant remember the exact details. Here is the log i think when it broke and here is a twitch clip of it https://www.twitch.tv/videos/787276927?t=01h32m38s .
[2020.10.29.18.34.49.log](https://github.com/Zingabopp/MultiplayerExtensions/files/5471508/2020.10.29.18.34.49.log)

**Comment by hpenney2** [comment]
> possibly if the host doesnt have the suggested song cant remember

That's correct, however, from my experience, the issue resolves itself after the song finishes downloading (roughly 5-15 seconds, you'll know it's done when you see the `SongCore Loader` text pop up). Clicking `Cancel` in the lobby seems to breaks it though and forces you to create a new lobby to resolve the issue. It would be nice if the mod showed some sort of visual indicator to know that it didn't break, though. Maybe also disable the `Cancel` button after the countdown finishes?

**Comment by hamcoremusic** [comment]
https://github.com/Zingabopp/MultiplayerExtensions/issues/23#issuecomment-726308748

Essentially what was posted above

**Comment by Goobwabber** [comment]
not an issue in the newest version
