### ISSUE TITLE
WIP songs are broken

### ISSUE THREAD

**Issue by rfcaps** [Zingabopp/MultiplayerExtensions#26]
There's an issue with loading any of the custom WIP songs. Fails to load song data and gives this error:

`O @ 19:11:33 | MultiplayerExtensions] Attempting to download custom level...
[ERROR @ 19:11:33 | MultiplayerExtensions] Error downloading beatmap 'custom_level_25372AB3B56F4B4EEB1DF17F1AFEE415290754D8_Nameless_-_Aishite WIP': Object reference not set to an instance of an object
[DEBUG @ 19:11:33 | MultiplayerExtensions] System.NullReferenceException: Object reference not set to an instance of an object
[DEBUG @ 19:11:33 | MultiplayerExtensions]   at MultiplayerExtensions.Downloader+<DownloadSong>d__2.MoveNext () [0x000ac] in <1f9244e0b9d8428887cfc85b69935ee6>:0 
[DEBUG @ 19:11:33 | MultiplayerExtensions] --- End of stack trace from previous location where exception was thrown ---
[DEBUG @ 19:11:33 | MultiplayerExtensions]   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <437ba245d8404784b9fbab9b439ac908>:0 
[DEBUG @ 19:11:33 | MultiplayerExtensions]   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess (System.Threading.Tasks.Task task) [0x0003e] in <437ba245d8404784b9fbab9b439ac908>:0 
[DEBUG @ 19:11:33 | MultiplayerExtensions]   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (System.Threading.Tasks.Task task) [0x00028] in <437ba245d8404784b9fbab9b439ac908>:0 
[DEBUG @ 19:11:33 | MultiplayerExtensions]   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd (System.Threading.Tasks.Task task) [0x00008] in <437ba245d8404784b9fbab9b439ac908>:0 
[DEBUG @ 19:11:33 | MultiplayerExtensions]   at System.Runtime.CompilerServices.TaskAwaiter`1[TResult].GetResult () [0x00000] in <437ba245d8404784b9fbab9b439ac908>:0 
[DEBUG @ 19:11:33 | MultiplayerExtensions]   at MultiplayerExtensions.HarmonyPatches`

**Comment by Goobwabber** [comment]
All players have to have the custom song to play it, the mod will not automatically download a wip song, as it does not exist on beatsaver.

**Comment by rfcaps** [comment]
I understand that. i’m saying in the solo mode this mod breaks WIP songs

**Comment by Zingabopp** [comment]
Can you include the full log file so we can see which build you're using? This should've been fixed awhile ago.

**Comment by Zingabopp** [comment]
Actually, yes, you are using an outdated build from before this was fixed. Get the latest from Actions and you should be good to go.
