### ISSUE TITLE
Songs will be always be downloaded even if a user already has the song

### ISSUE THREAD

**Issue by hpenney2** [Zingabopp/MultiplayerExtensions#27]
#### Issue Description

When the host selects a song, all other users in the lobby will download the song, regardless of if the user already has the song downloaded.

#### Steps to Reproduce

1. Create a lobby with MultiplayerExtensions installed and turn on custom songs
2. Have another user join the lobby with a specific song downloaded that you also have
3. Select the song they have downloaded already
4. Press `Start` and have the other user ready up (just in case, to force a download)

#### Expected Result

- The mod should use the user's already downloaded version of the song.

#### Actual Result

- The mod unnecessarily downloads the song again which also ends up showing the song twice when looking in the song list.

#### Additional Notes

A possible solution could be searching for the level hash in a user's song list.

**Comment by Zingabopp** [comment]
It should already be checking if the song exists before downloading. Try this build and post your log if the issue persists.
https://github.com/Zingabopp/MultiplayerExtensions/actions/runs/342205586

**Comment by hpenney2** [comment]
> Keep in mind that you could have different versions of the same song if the mapper made changes and reuploaded to Beat Saver.

Unlikely, one of the songs in question only has one version of the map published by the same mapper. I will try to test as soon as I can with the new build.
