### ISSUE TITLE
Different songs played by players?

### ISSUE THREAD

**Issue by Squares2020** [Zingabopp/MultiplayerExtensions#28]
I just joined a random lobby using the song browser mod and everything was smooth when I was spectating as usual. As soon as they all eventually chose a song the count down started except I was put into the game when the timer was at 2. I didn't think much of it until everyone was swinging and getting higher than me but there were no notes yet on my screen/game. The song was only about 1:26 and I played it like normal and eventually beat everyone but when the end of the song came everyone was still cutting notes and raising their score despite it being on the score screen showing as if I was the only one who played. When I got back to the lobby everyone was cutting in sync as if their song was still going but yet I was still in the lobby since the song finished for me. I waited about a minute to see if it was really only that 2 second delay in the beginning but they kept going for a while so I eventually just left. Thought it would be best to post it here but I'm unsure if this is the mods fault or not.

**Comment by Zingabopp** [comment]
If the host changed songs rapidly (and you didn't have two or more of them), there's a race condition in the downloader patch that may have caused this. This was brought to my attention in #27 and I'm working on a fix.
