### ISSUE TITLE
Mod broken/incompatible with other mods+players

### ISSUE THREAD

**Issue by TwinkieShip** [Zingabopp/MultiplayerExtensions#30]
For a normal custom song this is perfect but there is a bug for songs using extensions and other custom stuff.
In the video I show what it should be and works perfectly alone or with others spectating but when other players are in playing the song it breaks and duplicates the other players notes and walls making it impossible to play the map. At the end of the video you can literally see when other players die the bugged notes fizzle out, also the mod Chroma doesn't work to change the color to what the map wants.

https://youtu.be/kD67zKPzh9o
[_latest.log](https://github.com/Zingabopp/MultiplayerExtensions/files/5485025/_latest.log)

Used build "MultiplayerExtensions-0.1.2-bs1.12.2-37bc6d0"

**Comment by Zingabopp** [comment]
All of these issues are with those mods not handling multiplayer correctly and will have to be fixed on their end.
