### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by adlwar137** [Zingabopp/MultiplayerExtensions#36]
upon playing a song in multiplayer it just goes to a black screen

here's the log
[_latest.log](https://github.com/Zingabopp/MultiplayerExtensions/files/5490930/_latest.log)

**Comment by Zingabopp** [comment]
This is likely an issue with another mod.

**Comment by adlwar137** [comment]
Yep that was the issue, is there any way these two mods will be able yo work in the future.

**Comment by Zingabopp** [comment]
The issue isn't that MultiplayerExtensions breaks SaberFactory, it's that SaberFactory doesn't work in multiplayer at all.
