### ISSUE TITLE
Custom songs option does not appear

### ISSUE THREAD

**Issue by tailmaw** [Zingabopp/MultiplayerExtensions#37]
Once the mod is installed, on my end i do not have the option to turn on custom songs in multiplayer. 
i have the latest build and every build ive tried will not let me enable it in the mods menu once im in game my friend can pick custom songs and i can play them but i cant pick them myself or even see the menu option

**Comment by defvs** [comment]
We had that issue, you need to clear all mods (from ModAssistant options), reinstall IPA, SongCore, etc... after the update to 1.12
Seems like its an issue with the mod loader that doesn't run the mods unless you reinstalled completely

**Comment by Zingabopp** [comment]
If you still can't get it, ask for help in #pc-help in the BSMG Discord.
