### ISSUE TITLE
Softlocked after starting a song

### ISSUE THREAD

**Issue by Matt-but-GitHub** [Zingabopp/MultiplayerExtensions#38]
When attempting to start a song while in a lobby, the screen goes black and does not load anything in, and the game must be closed and reopened to continue. This happens 100% of the time for me and I've heard a few others mention it, but it doesn't seem to happen to many people or very often.

**Comment by Zingabopp** [comment]
You didn't post a log, but I'm guessing this is a duplicate of #36 (issue with SaberFactory that has to be fixed by SaberFactory)
