### ISSUE TITLE
[BUG] joining lobby and not showing custom songs at selection

### ISSUE THREAD

**Issue by Adminbnc** [Zingabopp/MultiplayerExtensions#46]
**Your Platform**
PC, Steam.

**Describe the bug**
So i cant join my friends lobby whenever i try it just sends me back to multiplayer selection mode and if my friend tried to join my lobby it just shows him black screen and also my friend can select custom songs but i can't even when i join a server or make my own.

**To Reproduce**

1. Create your own server / let your friend create a server
2. Join via code or let your friend join via code
3. See error.

**Expected behavior**
To basically join the lobby and play custom songs together.

**Log**
[_latest.log](https://github.com/Zingabopp/MultiplayerExtensions/files/5540810/_latest.log)

**Screenshots/Video**
Cannot send Video/Image.

**Additional context**
No additional context.

**Comment by Zingabopp** [comment]
You didn't install the mod correctly, but getting loaded. Check the installation instructions to make sure you're putting the files in the right place.
