### ISSUE TITLE
[BUG] Custom songs not showing in selection for some people??

### ISSUE THREAD

**Issue by Adminbnc** [Zingabopp/MultiplayerExtensions#48]
**Your Platform**
PC, Steam

**Describe the bug**
When I wanted to play with my friend again its just switched. I CAN select a custom song but when I select one it just doesn't show up for him. Please fix this.

**To Reproduce**
1. Join a lobby
2. Click on Select Song
3. You may not see the custom songs logo.

**Expected behavior**
To see the custom songs logo and succesfully select one.

**Log**
[_latest.log](https://github.com/Zingabopp/MultiplayerExtensions/files/5540968/_latest.log)

**Screenshots/Video**
No screenshot/Video.

**Additional context**
My friend is telling me that he can't see the song everytime I select a custom song.

**Comment by Zingabopp** [comment]
I would need his log since you're not having the issue.

**Comment by Adminbnc** [comment]
he is currently afk, i will send you the log as he comes back.

**Comment by Adminbnc** [comment]
There you go.
[latest.log](https://github.com/Zingabopp/MultiplayerExtensions/files/5541327/latest.log)

**Comment by Zingabopp** [comment]
He needs to update his mods:
`[WARNING @ 18:50:53 | IPA/Loader] MultiplayerExtensions is missing dependency BS Utils@^1.6.3`
