### ISSUE TITLE
[FEATURE] Scoresaber Support

### ISSUE THREAD

**Issue by ImFascinated** [Zingabopp/MultiplayerExtensions#49]
**Is your feature request related to a problem? Please describe.**

When I played ranked songs in multiplayer I have to try and not beat my previous best score because if I do it wont upload to scoresaber then I need to beat that score again not in multiplayer for it to upload to scoresaber and it just ruins all of the fun for playing on multiplayer for me and my friends. 

**Describe the solution you'd like**

Adding scoresaber score uploading support.

**Additional context**

None!

**Comment by Goobwabber** [comment]
this is an issue with scoresaber
