### ISSUE TITLE
[BUG] issues with noodle extensions

### ISSUE THREAD

**Issue by TropheusJ** [Zingabopp/MultiplayerExtensions#55]
**Your Platform**
quest 1 + oculus link, beat saber 1.13.0 on steam. running with `-vrmode oculus` to run without steam vr. 

**Describe the bug**
maps using noodle extensions are completely broken, with duplicated notes and static objects that should not be static. 

**To Reproduce**
install both multiplayer extensions and noodle extensions (https://github.com/Aeroluna/NoodleExtensions). host a multiplayer game and play a song that uses noodle extensions. for example, https://bsaber.com/songs/da60/. you will notice that quite a lot is messed up compared to singleplayer. 

**Expected behavior**
the map should work the same or almost the same as in singleplayer. 

**Log**
[latest log.zip](https://github.com/Zingabopp/MultiplayerExtensions/files/5586616/latest.log.zip)

log from `\Beat Saber\Logs\MultiplayerExtensions` in case it's useful too
[_latest.log](https://github.com/Zingabopp/MultiplayerExtensions/files/5586613/_latest.log)

**Additional context**
not sure if this needs to be fixed on multiplayer extensions's side or noodle extensions's side. 
mapping extensions seems to work fine in multiplayer.
this is not hardware specific, happens on WMR too. 
may require at least one extra player (2 total, including host) in the lobby for notes to duplicate.

**Comment by Zingabopp** [comment]
This is almost certainly a NoodleExtensions problem. The game does things differently in multiplayer (with or without MultiplayerExtensions).

**Comment by TropheusJ** [comment]
I'll report it to them instead, thanks for the response.
