### ISSUE TITLE
[BUG] vertical hud breaks hud in singleplayer

### ISSUE THREAD

**Issue by zivoy** [Zingabopp/MultiplayerExtensions#56]
**Your Platform**

HTC VIVE done normally through steam

**Describe the bug**

basically, the hud gets pushed into the roof when vertical hud is enabled 

**To Reproduce**

1. Go into the solo mode level selector and under the left menu in MODS > MULTIPLAYER, enable vertical hud but not single player hud
1.1. you can play a map and the hud should be fine
2. go back to the menu and play an online match
3. go back into singleplayer and play a map, the hud should be on the roof
4. if you disable vertical hud it will return to how it should be but will return to being on the roof when reenabled 

**Expected behavior**

a normal ui

**Log**

[_latest.log](https://github.com/Zingabopp/MultiplayerExtensions/files/5594200/_latest.log)

**Screenshots/Video**

settings:
![20201124210858_1](https://user-images.githubusercontent.com/16857861/100178087-3e041780-2ea1-11eb-822a-fcf19aae0901.jpg)
the bug, it got pushed up to the roof above yur:
![20201124210741_1](https://user-images.githubusercontent.com/16857861/100178126-4eb48d80-2ea1-11eb-8879-01ac15fff3ed.jpg)
with vertical hud disabled:
![20201124210812_1](https://user-images.githubusercontent.com/16857861/100178152-596f2280-2ea1-11eb-8692-41bcc49d8b86.jpg)

**Additional context**

idk

**Comment by Goobwabber** [comment]
Interesting issue.. looks like the method to disable toggles in singleplayer does not get called here. Likely a conflict with another mod. This is another bug that should be fixed when 0.4.0 releases.
