### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by jessidion** [Zingabopp/MultiplayerExtensions#58]
**Your Platform**
 Windows 10 Pro

**Describe the bug**

My friend is missing games, I see like 14 modded games, he only sees 2, and of course, he doesn’t see mine. He intalled everything like me together.

**To Reproduce**

I’m sorry don’t really know
**Expected behavior**

**Log**

It’s my friend’s I don’t know :/
**Screenshots/Video**

**Additional context**

**Comment by Zingabopp** [comment]
I'm guessing this is an issue for [Server Browser](https://github.com/roydejong/BeatSaberServerBrowser) and if you and your friend are mixing Oculus store and Steam store versions it's not a bug at all (there's no crossplay yet).

**Comment by jessidion** [comment]
> I'm guessing this is an issue for [Server Browser](https://github.com/roydejong/BeatSaberServerBrowser) and if you and your friend are mixing Oculus store and Steam store versions it's not a bug at all (there's no crossplay yet).

Actually didn’t know he bought it from oculus store thank u. Bruh tho 🤦🏻
