### ISSUE TITLE
[BUG] Can't host server, Can't see partner move when song is playing

### ISSUE THREAD

**Issue by SmilesOBrien** [Zingabopp/MultiplayerExtensions#60]
**Your Platform**

Steam, Oculus Rift (original)
Windows 10 Home 20H2

**Describe the bug**

When I host a game, partner cannot join - enters code and gets booted back to multiplayer options screen
When partner hosts game, I can't see their avatar in the lobby, or their name in the list. I can see them in default pose in game, and their boxes sliced, but the avatar does not move.

**To Reproduce**

1. Launch multiplayer mode and either host a game (which fails) or join a game which works, but with the above-described issue
2. Not really certain who else is experiencing this or what is causing it to advise, but it happens every time without fail for me.

**Log**

[Me_Host_Log.zip](https://github.com/Zingabopp/MultiplayerExtensions/files/5648099/Me_Host_Log.zip)
[Friend_host_log.zip](https://github.com/Zingabopp/MultiplayerExtensions/files/5648100/Friend_host_log.zip)

**Additional context**
I have tried disabling both router and windows firewall to see if it was a network issue, which didn't resolve the problem so far as I could tell. I've disabled real time scanning on my Antivirus (Webroot) which also didn't help.

As far as I can tell, this issue started after installing the MultiplayerExtensions mod. Prior to that (after installing all required mods but before installing MultiplayerExtensions), regular multiplayer worked outwithout issue

**Comment by Zingabopp** [comment]
Make sure you're both on the latest build, looks like you're both using an old one.

**Comment by SmilesOBrien** [comment]
Ah, Got it, new to GitHub, thought I had the latest but I understand now. I'll try this out tomorrow and confirm.

**Comment by SmilesOBrien** [comment]
Confirmed, that was the source of this particular issue
