### ISSUE TITLE
First custom song not loading properly

### ISSUE THREAD

**Issue by rakso20000** [Zingabopp/MultiplayerExtensions#7]
When starting the first custom song I didn't have, I entered the game as a spectator, it said I didn't own the song, and neither music nor beatmap did play. Afterwards I left the lobby and saw the map was actually properly downloaded and available. I was also able to play it in multiplayer when rejoining the lobby. After that it worked like a charm, downloading the songs just before starting.

**Comment by rakso20000** [comment]
[And here's the log](https://github.com/Zingabopp/MultiplayerExtensions/files/5435831/2020.10.24.18.01.57.log)

**Comment by Goobwabber** [comment]
fixed
