### ISSUE TITLE
[BUG] Cannot download other host's songs

### ISSUE THREAD

**Issue by FireFtw** [Zingabopp/MultiplayerExtensions#74]
**Your Platform**
PC w/ Steam. Using Vive pro.

**Describe the bug**
Attempting to download and play a song another user already has installed doesn't do anything. Extention throws exception. Testing with two other users who also have the same version + same mod manager setup.

**To Reproduce**
Create a multiplayer lobby and have another user join. Choose a song they don't have and start the game. Your other player will stay in the lobby while you are sent into game with only a playform and no notes. 

Or from the other side:
Join a player's loby. Song in front displays "Not defined" when you select the user on the right to select the same song.

**Expected behavior**
Song is downloaded and user joins host in game.

**Log**
[_latest.log](https://github.com/Zingabopp/MultiplayerExtensions/files/5762460/_latest.log)

**Additional context**
Mod manager setup
![modmanager1](https://user-images.githubusercontent.com/6172118/103491630-10d54e00-4deb-11eb-990a-89e5ef896cc8.png)
![modmanager2](https://user-images.githubusercontent.com/6172118/103491631-116de480-4deb-11eb-81df-556c2c3897ee.png)

**Comment by Nyx-WildSiren** [comment]
I have had the same issue with 5 people in a lobby.

**Comment by Daniele1926** [comment]
same problem

**Comment by sam5776** [comment]
Same issue with two other people

**Comment by scootah24** [comment]
I problem too

**Comment by senacand** [comment]
I think this is the user agent issue, which should've been fixed in the [last build](https://github.com/Zingabopp/MultiplayerExtensions/actions/runs/459818429).

**Comment by SirLynix** [comment]
Had the same issue with the last release

**Comment by Zingabopp** [comment]
@SirLynix Please post a log from the game session you had this happen in.

**Comment by SirLynix** [comment]
Here you are:
[host.zip](https://github.com/Zingabopp/MultiplayerExtensions/files/5777685/host.zip)
[client.zip](https://github.com/Zingabopp/MultiplayerExtensions/files/5777687/client.zip)

This was with my gf (we were using Discord for voice), she was the host most of the time (hosting) and I was client most of the time (joined her server).

I did look at them and it seems to be normal log, however we were having serious issues in game:  
1) First she put "Diggy diggy hole" which I had to download, had no trouble with that (song got downloaded and we played it without any issue).
2) Then we tried with another song, Waka Waka. It didn't seem to work well (she was ingame and I was still in the lobby, and she told me she was waiting with a black screen, had to restart the game).
3) I downloaded the song using BeatSaverDownloader ("More song" menu) and then it seemed like we were out of sync, I couldn't see the song she selected and she didn't see the song I selected. Worse than that sometimes she had the timer for starting and I didn't. And when we played songs we already had we were out of sync (like her music started around 10s before mine, and I finished ~10s after her).

I'm really not sure what the hell happened, we restarted the game several times and it didn't seem to fix the issues, and then we gave up.

**Comment by Zingabopp** [comment]
Do you have BeatTogether, or just MultiplayerExtensions?

**Comment by SirLynix** [comment]
Just MultiplayerExtensions, 0.4.1 (last release)

**Comment by Unkn0wnNode** [comment]
Same thing here

**Comment by craftthiss** [comment]
Similarly if one player fails to download the song and is still in the lobby the other player is stuck in a empty dusty void until he quits.

**Comment by FireFtw** [comment]
Updating to the newest version got me working again.
