### ISSUE TITLE
[FEATURE] Where do I buy you a coffee?

### ISSUE THREAD

**Issue by ThePheonixGuy** [Zingabopp/MultiplayerExtensions#75]
**Is your feature request related to a problem? Please describe.**
This mod has literally re-invigorated the game for me, and allows me such an easy way to jam out with friends and share all the cool songs we find with each other.

And yet, for all it's awesomeness, I can't contribute!

I'm a dev but this is out of my scope entirely, and I'd love to make some small contribution for this work that, IMO, makes the game for me

**Describe the solution you'd like**
Sign up with someone like https://www.buymeacoffee.com/ and let those who want to donate, donate!

**Comment by Goobwabber** [comment]
My ko-fi link is in my Github readme but I'll link it here for convenience https://ko-fi.com/goobwabber

**Comment by Zingabopp** [comment]
Donation links have been added to the readme, thank you for your support!
