### ISSUE TITLE
Multiplayer Extension Not Detected, Hiding Modded Games

### ISSUE THREAD

**Issue by Rexdog32** [Zingabopp/MultiplayerExtensions#77]
Steam, Oculus Rift-S

In the song browser, it says: MultiplayerExtension not detected, hiding modded games.

When I click Multiplayer then I click song browser, it says that on the bottom.

To, well, show modded games.
I think this is the log: [INFO @ 12:14:09 | _] [ScoreSaber] [Info] Loading ScoreSaber... 
[INFO @ 12:14:09 | _] [ScoreSaber] [Info] ScoreSaber Loaded... 
[INFO @ 12:14:25 | _] SongBrowser Plugin Loaded()

![20210104122352_1](https://user-images.githubusercontent.com/71905411/103566670-04530300-4e88-11eb-86f8-f7de6b1b875b.jpg)
It's a little hard to see.

Nothing.

**Comment by Goobwabber** [comment]
are you sure you actually have it installed properly? you need the dependencies as well

**Comment by Xplycite** [comment]
Hey i'm having issues with the same thing, any notes on what might not be installed properly

**Comment by JustGoEzOnMe** [comment]
Hi, im in the same boat :(
