### ISSUE TITLE
[BUG] Double Notes with Noodle Extensions

### ISSUE THREAD

**Issue by WiredG1** [Zingabopp/MultiplayerExtensions#79]
PC

When playing a song with noodle extensions a second note will appear and start turning the wrong way. This extra note is unhittable. It seems to not be a problem when one of the two players die. This is making me think that the second players notes are in the wrong "lane". Used song in the video: https://beatsaver.com/beatmap/11cf8
Link to video: https://1drv.ms/u/s!AkaSnPycUYb2h2nrnuuaBo-nOM8Q?e=2aqVoP

**Reproduce**
1. Start multiplayer server with 2 players
2. Select song with noodle extensions
3. Double notes
[_latest.log](https://github.com/Zingabopp/MultiplayerExtensions/files/5791656/_latest.log)

**Comment by Zingabopp** [comment]
This is purely a NoodleExtensions issue.
