### ISSUE TITLE
WIP songs not loading with MultiplayerExtensions installed

### ISSUE THREAD

**Issue by rakso20000** [Zingabopp/MultiplayerExtensions#8]
Trying to access WIP songs with the mod installed, it just said 'Couldn't load data' or something like that. There was a reload button but clicking it didn't resolve the issue.
According to the log MultiplayerExtensions was trying and failing to download maps when I tried loading the WIPs.
[Log here](https://github.com/Zingabopp/MultiplayerExtensions/files/5438668/multi.log)

**Comment by rakso20000** [comment]
It worked again after I uninstalled MultiplayerExtensions.

**Comment by Zingabopp** [comment]
This should be fixed in later builds? Make sure you using the latest one and let me know.

**Comment by rakso20000** [comment]
Yup 👍
Seems to be working now.
