### ISSUE TITLE
[Info/Question] Missing dependency of "Ini Parser 2.5.7+" ?

### ISSUE THREAD

**Issue by RicoR3** [Zingabopp/MultiplayerExtensions#81]
Should the required dependency "Ini Parser@^2.5.7" be added to the documentation?
After manually installing the listed required mods, the lack of the "Ini Parser"-mod caused "BS Ultis" not to load for me, and as a result, "SongCore" does not load aswell.
After downloading and adding it manualy from https://beatmods.com/  it works fine for me. 

May have happened to me by using Revive (Oculus version of BeatSaber via Index VR).

Could someone double check this?

**Comment by Zingabopp** [comment]
Listing dependencies of dependencies isn't really worth it. It's up to the people manually installing mods to make sure they have the dependencies for the mods (like BS Utils) they're installing.
