### ISSUE TITLE
[FEATURE] Option to disable rendering other player's copy of the beatmap

### ISSUE THREAD

**Issue by harry1453** [Zingabopp/MultiplayerExtensions#91]
**Is your feature request related to a problem? Please describe.**
The problem is mainly performance issues, **especially** when playing levels that use Chroma/Mapping Extensions. The maps work fine but is very slow due to rendering multiple copies of resource intensive maps.

**Describe the solution you'd like**
A toggle to disable rendering other player's blocks / walls etc. Even better would be if the mod could auto-detect when mapping extensions or other slower mods are being used and automatically disable rendering other player's copies of the map. This might also fix Noodle extensions (as noodle extensions works in MP with only one player)

**Comment by A-plou** [comment]
well Noodle Extension doesn't work at all if the map have the teleport pov thing, it won't change the pov in multiplayer so that wouldn't really fix Noodle Extension. Maybe that will reduce a lot of lag, but not completely

**Comment by harry1453** [comment]
Okay, noodle extensions was just a side thought. Mapping extensions maps have extremely poor performance but do work perfectly.

**Comment by Goobwabber** [comment]
Implemented in #117
