### ISSUE TITLE
[BUG] Mod Assistant shows 0.4.3 as newest Version (outdated entry in BeatMods)

### ISSUE THREAD

**Issue by david-kalbermatten** [Zingabopp/MultiplayerExtensions#98]
**Your Platform**

PC, Steam Version

**Describe the bug**

The title says it all. But here a screenshot of the issue:
![image](https://user-images.githubusercontent.com/45201085/107948741-8ad52700-6f94-11eb-89fa-f8a973e18936.png)
[https://beatmods.com/#/mods](https://beatmods.com/#/mods)

**To Reproduce**

1. Open Mod Assistant
2. Look at the `latest` version number of MultiplayerExtensions

**Expected behavior**

Should be the same version as the latest release on this Github repo. At the time of writing, this would be `0.4.4`, not `0.4.3`.

**Comment by Goobwabber** [comment]
yeah, I haven't submitted the newest version to modassistant since there are some bugs I'm working out.
